version: '3'
services:
  hue:
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/hue:4.0.0
    networks:
    - parrot
    external_links:
    - hive
    - hadoop
    - zookeeper
    - postgres
    environment:
      PGPASSWORD: postgres
    ports:
    - 8000:8000
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge
volumes:
  hadoop_conf: null
  hive_conf: null
  hbase_conf: null
